### ISSUE TITLE
Unauthorized

### ISSUE THREAD

**Issue by bjorn** [bill-auger/lctv-badges#3]
I had to remove my badge because it always says "Unauthorized".

Since also the new location at https://tools.liveedu.tv/badges is not working for me (I'm failing to login), I was trying the links here again but still no luck.

I've written to LiveEdu support about the login problem. Is there maybe some way to get the badges here to work again? Why are they not unauthorized, given that whether I'm streaming or not is public information, isn't it?

**Comment by bill-auger** [comment]
are you saying that you are getting "Unauthorized" from my demo instance?

i really never planned for anyone to use that permanently but i suppose can try to fix it if the official one is broken - i dont have anything to do with the official site tho so i can not help with that

it should not go without saying tho that this project was designed to be hosted by anyone - if you have a server of your own you can clone this repo to your server and have it setup in minutes

**Comment by bjorn** [comment]
> are you saying that you are getting "Unauthorized" from my demo instance?

I mean that I followed a link from the README.md and filled in my LiveEdu username there:

http://codiad-billauger.rhcloud.com/demos/?title=Online%20Status%20-%20Logo%20Pill&badge-style=online-status-v2

Then clicked the "Demo" button, and the badge that spawns always says "Unauthorized".

> i really never planned for anyone to use that permanently but i suppose can try to fix it if the official one is broken - i dont have anything to do with the official site tho so i can not help with that

It's weird that you should say that, because the official page actually links to this very issue tracker:

_"More styles and features to come once the LCTV REST API is finalized - feel free to post any comments or suggestions to the [issue tracker](https://github.com/bill-auger/lctv-badges/issues)"_

> it should not go without saying tho that this project was designed to be hosted by anyone - if you have a server of your own you can clone this repo to your server and have it setup in minutes

In that case, you may want to write something in the README.md about how to get started, because at the moment it just directs people to your server.

**Comment by bill-auger** [comment]
yea maybe i should put a link to the instructions - the instructions are in the repo for the API-wrapper which is a submodule of this repo

https://github.com/bill-auger/lctv-api/

it sounds like maybe the API server itself is not responding - how long has this been broken?

**Comment by bjorn** [comment]
> yea maybe i should put a link to the instructions - the instructions are in the repo for the API-wrapper which is a submodule of this repo

Ah, hmm. Well, I guess I would get stuck already at the web server set up and wouldn't get to the part of filling in the configurations. It's been years since I did anything with PHP...

> it sounds like maybe the API server itself is not responding - how long has this been broken?

For at least two months.

**Comment by bill-auger** [comment]
@taddeimania -

do you know what's the deal with the LCTV API? the badges have stopped working - both this demo instance and on the official site - and i can not even log into the API site

**Comment by taddeimania** [comment]
@bill-auger 

did you see that they moved to a new domain?

https://www.liveedu.tv/developer/applications/

Maybe urls need to be updated? I haven't associated myself with LCTV for a while so i'm not sure if the rebranded site isn't working.

**Comment by taddeimania** [comment]
woops sorry i just read this thread, you are well aware of the change. Yeah I would assume they are experiencing difficulties - but honestly this is one of the reasons i distanced myself from them. Very sub par org.

**Comment by bill-auger** [comment]
@taddeimania -

thanks for answering - that link you posted is the one i mentioned where you log into the API but the login is broken - the livecoding.tv domain redirects to the new domain so i dont think that is the problem - according to bjorn the "difficulties" have been for 2 months - bjorn tried to contact them but im guessing there was no response

**Comment by bjorn** [comment]
> bjorn tried to contact them but im guessing there was no response

Only an automatic response so far, but I contacted them just before opening this issue. Normally they get back in about a day, so let's see what they say.

**Comment by bill-auger** [comment]
@bjorn - 

i hate to say but it looks like they may have killed the badges along with the entire API - to be clear, when you see on the official badges page when you click the "embed code" button and it says "This app is not yet authorized. Login to authorize it." - that alert is not meant for the users to ever see - it is not asking you to login but it is saying that their badges website is not authorized to use their own API - it looks like the API itself is completely off

if you only wanted an online/offline button there was one in this repo way back when we were trying to figure out how to use the API that screen-scraped the live listing page for your nick - that may be the only way again

unfortunately taddeimania is not alone is his dismal view - many people have been turned off - i have not streamed there in about a year myself - ive worked with them fairly closely in the past and i can honestly say that i have never gotten a straight answer about any technical question ive asked - im talking pages full of questions but zero answers - and the few times i explicitly asked to put me in touch with someone on the dev team it never happened - this project is one that is unfortunately a bit more brittle and insecure than i would have liked it to be but i needed answers from the ppl who installed the API and i never got them - it seems to me that they may not even have a tech team but hire freelancers whenever something technical needs to happen - so this may be a case of something that broke and they either dont know it yet or not enough people have complained about missing the features so it may not be worth fixing - oddly enough that they presented it with such fanfare and these badges were actually their idea

anyway i will change the API URL tomorrow maybe that's the problem - if not theres not much else i can do unless they answer you about what is wrong with the API or when it is coming back online - that may help but im not so hopeful TBH

**Comment by bjorn** [comment]
@bill-auger Thanks for your detailed answer. I really hoped LCTV would be different, though personally I have been put off by their business model which dictates ads to viewers unless THEY sigh up as Pro, whereas I'd really prefer a site that allows ME to pay for ad-free streaming. The rebranding to LiveEdu also isn't helping my audience, since I'm not making premium tutorial videos (I mean who has the time for that? :-S).

Would you suggest any alternative? It's basically Twitch then, isn't it?

**Comment by bill-auger** [comment]
i could not recommend twitch at all - they did exactly the same thing with the ads to us about 10 years ago when it was still JTV - then they decided that JTV must die and only video game channels would be allowed on the new site

there is another one for gamers called beam that some of the LCTV refugees are using - but again like twitch is highly geared toward gamers so probably wont find an audience there unless you make games - there are others more general such as ustream, livestream, and youtube but would expect to find much of an audience for programming there either

there is only one other that is explicitly for programing http://www.watchpeoplecode.com/ but i dont think as many ppl use it yet - LCTV still is probably the only one where you may find a large audience

**Comment by taddeimania** [comment]
twitch may have burned folks in the past with JTV but they have a channel
specifically for programming called "Creative". Still tiny audiences
because it turns out people don't go to twitch to watch people write code.
They want to watch people play games or get drunk on camera.

**Comment by bill-auger** [comment]
@bjorn -

have you gotten a response from LCTV about this?

**Comment by bjorn** [comment]
@bill-auger Actually I never heard back from them, but I just checked and they did fix the login issue. However, I'm still not sure how to make an online/offline pill, since before you get the embed code you need to fill in the "Channel Name", and I have no idea what they want me to fill in there. I tried filling in my username or the name of my project, but in both cases I get a small text "Not found." visible at the top.

**Comment by bill-auger** [comment]
@bjorn -

ok i grabbed a wrench and opened the hood today and i was able to get the "Online Status" and "Number of Viewers" badges working again on the demo site http://codiad-billauger.rhcloud.com/ - plz let me know if yours work on your site too

like pfft - i would have tried last month if the main website's instance or the API site was working - the fact that they were both broken did not give me much hopefulness - they still are broken actually but i decided to poke it one last time

**Comment by bjorn** [comment]
@bill-auger Hmm, on your demo page and when using a direct link, the badge is working, but in my README.md it isn't for some reason: https://github.com/bjorn/tiled

**Comment by bill-auger** [comment]
ok that's a bug in the embed code output - all the spaces need to be URL escaped with ``'%20'``
```
![LiveEdu.tv](http://codiad-billauger.rhcloud.com/badges/?style=online-status-v1&channel=bjorn&offline=Follow%20to%20get%20notified)
```

either of the following forms are equivalent

HTML:
```
<a href="http://liveedu.tv/bjorn">
<img src="http://codiad-billauger.rhcloud.com/badges/?style=online-status-v1&channel=bjorn&offline=Follow%20to%20get%20notified"alt="LCTV onine status status"  />
</a>
```

markdown:
```
[![LCTV onine status status][lctv-status-img]][lctv-link]

[lctv-status-img]: http://codiad-billauger.rhcloud.com/badges/?style=online-status-v1&channel=bjorn&offline=Follow%20to%20get%20notified
[lctv-link]: http://liveedu.tv/bjorn
```

**Comment by bjorn** [comment]
@bill-auger Ok, that's strange because it worked with spaces before. Anyway, it's fixed now, thanks!

**Comment by bjorn** [comment]
@bill-auger One more thing: maybe it won't be too hard to update the LiveCoding.tv text on the badge to LiveEdu.tv? :-)

**Comment by bill-auger** [comment]
yes i going to push some changes today then i will update the server

**Comment by bill-auger** [comment]
@bjorn 

i see there was a token created for you today but im not sure how it got there - are you hosting a clone of this repo? - did you click the "authorize" link in api/authorize.php on my site or yours? were you otherwise asked to authorize the app on the LCTV API site at any point today?

just trying to understand this API more myself - as i said there was and still is no documentation for the API, they never answered any of my questions about it, and i havent asked anyone else to help test the badges - it was left as "it works for me" - i think some of the features may be broken but i would need to create a dummy account on LCTV or else someone else to try things

**Comment by bjorn** [comment]
@bill-auger I do not host a clone of this repository. Today I only fixed the link use %20 instead of spaces, and may have activated the "Demo" button on your site one more time.

**Comment by bill-auger** [comment]
ok i think thats explains it - thanks
